name : CI

on:
  push:
    branches: [ feat/github-actions ]
  
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Log in to github container registry
        uses: docker/login-action@v4
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
